In [147]:
import numpy as np
r_40 = np.array([-5,-4,-3,-2,-1,0])
print(r_40)

[-5 -4 -3 -2 -1  0]


In [148]:
a_40 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a_40)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [149]:
t_40 = np.array([[[0,1,2,3,4,5],[4,5,6,7,8,9]],[[8,9,8,7,6,5],[6,5,4,3,2,1]],[[1,2,3,4,5,6],[-5,-4,-3,-2,-1,0]]])
print(t_40)

[[[ 0  1  2  3  4  5]
  [ 4  5  6  7  8  9]]

 [[ 8  9  8  7  6  5]
  [ 6  5  4  3  2  1]]

 [[ 1  2  3  4  5  6]
  [-5 -4 -3 -2 -1  0]]]


In [150]:
r_40.ndim

1

In [151]:
a_40.ndim

2

In [152]:
t_40.ndim

3

In [153]:
r_40.shape

(6,)

In [154]:
a_40.shape

(2, 6)

In [155]:
t_40.shape

(3, 2, 6)

In [156]:
i_40 = np.array([[4,5,6,7,8],[9,10,11,12,13],[14,15,16,17,18]])
print(i_40)

[[ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]]


In [161]:
i_40[0,1]

5

In [162]:
i_40[0,2]

6

In [163]:
i_40[0,0]

4

In [164]:
i_40[1,2]

11

In [165]:
i_40[1,3]

12

In [166]:
i_40[1,4]

13

In [167]:
i_40[2,2]

16

In [168]:
i_40[2,3]

17

In [169]:
i_40[2,1]

15

In [170]:
i_40[1,:]

array([ 9, 10, 11, 12, 13])

In [171]:
i_40[0,:]

array([4, 5, 6, 7, 8])

In [172]:
i_40[2,:]

array([14, 15, 16, 17, 18])

In [173]:
i_40[:,0]

array([ 4,  9, 14])

In [174]:
i_40[:,1]

array([ 5, 10, 15])

In [175]:
i_40[:,2]

array([ 6, 11, 16])

In [176]:
i_40[0,1:2]

array([5])

In [177]:
i_40[0,1:3]

array([5, 6])

In [178]:
i_40[1,2:4]

array([11, 12])

In [179]:
i_40[2,1:3]

array([15, 16])

In [180]:
i_40[0,0:1:2]

array([4])

In [181]:
i_40[0,0:5:4]

array([4, 8])

In [182]:
i_40[1,2] = 27
print(i_40)

[[ 4  5  6  7  8]
 [ 9 10 27 12 13]
 [14 15 16 17 18]]


In [183]:
k_40 = np.ones((10,10))
print(k_40)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [184]:
l_40 = np.identity(10)
print(l_40)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [185]:
m_40 = 5*l_40
print(m_40)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [186]:
n_40 = np.full((4,3),5)
print(n_40)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [187]:
o_40 = np.random.rand(7,5)
print(o_40)

[[0.34775452 0.89503604 0.65871689 0.60945817 0.83932097]
 [0.35689091 0.24843822 0.97582457 0.01999871 0.28187629]
 [0.24880021 0.63737878 0.93550603 0.02881067 0.4917042 ]
 [0.38298171 0.93019568 0.43868089 0.96247044 0.2898544 ]
 [0.65517279 0.24493242 0.37842366 0.64360932 0.70318257]
 [0.27930555 0.05160403 0.92337279 0.15966172 0.95223719]
 [0.72940693 0.56301352 0.05669077 0.92927412 0.27620078]]


In [188]:
p_40 = np.random.randint(1,6,size=(4,5))
print(p_40)

[[3 4 1 2 2]
 [5 5 4 3 2]
 [2 3 3 4 1]
 [3 4 4 2 5]]


In [189]:
q_40 = np.zeros((8,8))
s_40 = np.ones(8)*4
u_40 = q_40 + s_40
print(u_40)

[[4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]]


In [190]:
m_40[1:-1,1:-1] = u_40
print(m_40)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [191]:
w_40 = np.identity(6)*7
m_40[2:-2,2:-2] = w_40
print(m_40)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 7. 0. 0. 0. 0. 0. 4. 0.]
 [0. 4. 0. 7. 0. 0. 0. 0. 4. 0.]
 [0. 4. 0. 0. 7. 0. 0. 0. 4. 0.]
 [0. 4. 0. 0. 0. 7. 0. 0. 4. 0.]
 [0. 4. 0. 0. 0. 0. 7. 0. 4. 0.]
 [0. 4. 0. 0. 0. 0. 0. 7. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [192]:
e_40 = np.ones((4,4))*5
f_40 = np.identity(4)*7
g_40 = e_40 + f_40
print(g_40)

[[12.  5.  5.  5.]
 [ 5. 12.  5.  5.]
 [ 5.  5. 12.  5.]
 [ 5.  5.  5. 12.]]


In [193]:
m_40[3:-3,3:-3] = g_40
print(m_40)

[[ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  4.  4.  4.  4.  4.  4.  4.  0.]
 [ 0.  4.  7.  0.  0.  0.  0.  0.  4.  0.]
 [ 0.  4.  0. 12.  5.  5.  5.  0.  4.  0.]
 [ 0.  4.  0.  5. 12.  5.  5.  0.  4.  0.]
 [ 0.  4.  0.  5.  5. 12.  5.  0.  4.  0.]
 [ 0.  4.  0.  5.  5.  5. 12.  0.  4.  0.]
 [ 0.  4.  0.  0.  0.  0.  0.  7.  4.  0.]
 [ 0.  4.  4.  4.  4.  4.  4.  4.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]]


In [194]:
y_40 = np.identity(2)*7
m_40[4:-4,4:-4] = y_40
print(m_40)

[[ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  4.  4.  4.  4.  4.  4.  4.  0.]
 [ 0.  4.  7.  0.  0.  0.  0.  0.  4.  0.]
 [ 0.  4.  0. 12.  5.  5.  5.  0.  4.  0.]
 [ 0.  4.  0.  5.  7.  0.  5.  0.  4.  0.]
 [ 0.  4.  0.  5.  0.  7.  5.  0.  4.  0.]
 [ 0.  4.  0.  5.  5.  5. 12.  0.  4.  0.]
 [ 0.  4.  0.  0.  0.  0.  0.  7.  4.  0.]
 [ 0.  4.  4.  4.  4.  4.  4.  4.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]]


In [195]:
a_40 = np.array([2,3,4,5])
print(a_40)

[2 3 4 5]


In [196]:
b_40 = a_40
print(b_40)

[2 3 4 5]


In [197]:
b_40[0] = 0
print(b_40)

[0 3 4 5]


In [198]:
print(a_40)

[0 3 4 5]


In [199]:
c_40 = np.array([6,7,8,9])
print(c_40)

[6 7 8 9]


In [200]:
d_40 = c_40.copy()
print(d_40)

[6 7 8 9]


In [201]:
d_40[3] = 12
print(d_40)

[ 6  7  8 12]


In [202]:
print(c_40)

[6 7 8 9]


In [203]:
a_40+5

array([ 5,  8,  9, 10])

In [204]:
a_40-3

array([-3,  0,  1,  2])

In [205]:
a_40*4

array([ 0, 12, 16, 20])

In [206]:
a_40**3

array([  0,  27,  64, 125])

In [207]:
z_40 = np.array([7,8,9,10])
print(z_40)

[ 7  8  9 10]


In [208]:
a_40+z_40

array([ 7, 11, 13, 15])

In [209]:
a_40-z_40

array([-7, -5, -5, -5])

In [210]:
a_40*z_40

array([ 0, 24, 36, 50])

In [211]:
a_40/z_40

array([0.        , 0.375     , 0.44444444, 0.5       ])

In [212]:
z_40**a_40

array([     1,    512,   6561, 100000])

In [213]:
np.cos(a_40)

array([ 1.        , -0.9899925 , -0.65364362,  0.28366219])

In [214]:
np.sin(z_40)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [215]:
np.tan(a_40)

array([ 0.        , -0.14254654,  1.15782128, -3.38051501])

In [216]:
np.sinh(z_40)

array([  548.31612327,  1490.47882579,  4051.54190208, 11013.2328747 ])

In [217]:
np.cosh(a_40)

array([ 1.        , 10.067662  , 27.30823284, 74.20994852])

In [218]:
np.tanh(z_40)

array([0.99999834, 0.99999977, 0.99999997, 1.        ])

In [219]:
np.sqrt(a_40)

array([0.        , 1.73205081, 2.        , 2.23606798])

In [220]:
np.sqrt(z_40)

array([2.64575131, 2.82842712, 3.        , 3.16227766])

In [221]:
p_40 = np.array([[12,11,10,9,8,7],[6,5,4,3,2,1]])
print(p_40)

[[12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [222]:
q_40 = np.array([[2,3,4,5,6,7],[8,9,10,11,12,13]])
print(q_40)

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [223]:
r_40 = p_40*q_40
print(r_40)

[[24 33 40 45 48 49]
 [48 45 40 33 24 13]]


In [224]:
s_40 = np.array([[4,5],[6,7],[8,9],[10,11],[12,13],[14,15]])
print(s_40)

[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [225]:
v_40 = np.matmul(p_40,s_40)
print(v_40)

[[478 535]
 [154 175]]


In [228]:
e_40 = np.array([[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(e_40)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [229]:
f_40 = np.min(e_40)
print(f_40)

21


In [230]:
g_40 = np.min(e_40,axis=0)
print(g_40)

[21 22 23 24 25]


In [231]:
h_40 = np.min(e_40,axis=1)
print(h_40)

[21 26 31]


In [232]:
i_40 = np.max(e_40)
print(i_40)

35


In [233]:
j_40 = np.max(e_40,axis=0)
print(j_40)

[31 32 33 34 35]


In [234]:
k_40 = np.max(e_40,axis=1)
print(k_40)

[25 30 35]


In [235]:
l_40 = np.sum(e_40)
print(l_40)

420


In [236]:
m_40 = np.sum(e_40,axis=0)
print(m_40)

[78 81 84 87 90]


In [237]:
n_40 = np.sum(e_40,axis=1)
print(n_40)

[115 140 165]
